spring.application.name=c19_CRM_Project_1

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://localhost:3306/cmrdb_springboot
spring.datasource.username=root
spring.datasource.password=aditya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
